### PR TITLE
fix(types): restrict regular styles function call to one argument

### LINKED ISSUE #15: styled: multiple arguments not working(?)
I seem to have an issue with passing in multiple arguments to `styled`.
From what I can tell by the types, it should be possible to do the following
```Typescript
const Component = styled('div')(
  {
    display: 'inline-flex',
    width: '100%',
    height: '100%',
    border: '1px solid #222'
  },
  (props) => props.hidden && ({ display: 'none' }),
  (props) => props.rounded && ({borderRadius: '.3em' })
  ({
    background: '#f2f2f2'
  })
)
```
but that doesn't actually call or apply the arguments past the first one.
However, reading goober's manual they accept an array (https://github.com/cristianbote/goober#arrays) for using multiple arguments.
passing in an array to `styled` works and all the styles are computed and applied as expected, but the types doesn't seem to like that.
image

minimal reproducible example https://codesandbox.io/s/friendly-payne-ehyjo

### LINKED ISSUE #37: Inconsistency between styled's implementation and types
### Issue

The types allow for multiples arguments when styling a component. The following is correct based on [the types](https://github.com/solidjs/solid-styled-components/blob/main/src/index.d.ts#L35-L60).

```tsx
const Component = styled('div')(
  { color: "blue" },
  (props) => ({ color: props.theme.palette.primary }),
  () => ({ color: "pink" }),
  // ...
);
```

We could expected that a `textNode` passed to `Component` would be `pink`, but with the current implementation the result is `blue` _(the first argument)_.

It's due to the following lines:

https://github.com/solidjs/solid-styled-components/blob/dec99a0a51e1eaeb8783390291c09e4e436f046b/src/index.js#L47-L50

By looking at this code we could expected that the `textNode` would be `blue`. When we do the `apply` the second argument expected an array of arguments _(see: [apply doc](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/apply))_. Here the `args` variable represents all the argument passed to style the `div`. It's like if we were doing the folowing:

```tsx
// to simplify the `this` "assignment" isn't part of the example
css(
  { color: "blue" },
  (props) => ({ color: props.theme.palette.primary }),
  () => ({ color: "pink" }),
  // ...
);
```

The issue is that the `css` method from goober only take one argument. Everything after the first argument is ignored.

https://github.com/cristianbote/goober/blob/b2781bd9d76f5b386e50b5916216430f4532662c/src/css.js#L5-L9
```tsx
/**
 * css entry
 * @param {String|Object|Function} val
 */
function css(val) {
```

_Secondary issue: We could also take the time to improve the types, because currently there's no way to mark the `theme` prop as not optional an the `as` prop types should probably be `ValidComponent` instead of `string | number | symbol | undefined`_

---

### Proposed solution

**Only tag function should be allowed to have multiple arguments**

There's a way to make the tag function work while restricting regular function call to one argument. Based on what's happening in goober's [`css` function](https://github.com/cristianbote/goober/blob/b2781bd9d76f5b386e50b5916216430f4532662c/src/css.js#L5-L26), here's what the types could look like _(without the generic type for the props)_:

```tsx
import type { ValidComponent } from "solid-js";

type StylesGenerator = (props: {}) => CSSAttribute | string;
type StylesArg =
  | string
  | CSSAttribute
  | StylesGenerator
  | Array<CSSAttribute | StylesGenerator>;
type StylesFn = (styles: StylesArg) => Component
type TagStyleGenerator = (props: {}) => number | string | undefined;
type TagFn = (
  tag: TemplateStringsArray,
  ...args: Array<string | TagStyleGenerator>,
) => Component;

// This way we can both use a regular function call with
// one argument or a tag function with multiple arguments
type StylingFn = StylesFn & TagFn;
```

With these types the example at the beginning wouldn't be allowed and the types would fit the implementation.

Let me know what you think.

### PR DESCRIPTION
**Pull request by 100terres**
### What's included

fix: #37
fix: #15

Tag functions are properly typed and regular function calls are restrict to one argument (see: https://github.com/solidjs/solid-styled-components/pull/38#discussion_r988537281)
  - `keyframes`
  - `glob`
  - `css`
  - `createGlobalStyles`
  - The return of the `styled(...)`

We can now override the types to mark the `theme` as always available on the props. (see: https://github.com/solidjs/solid-styled-components/pull/38#discussion_r988531112)

### CODE REVIEW

File: src/index.d.ts [hunk 1]
```diff
@@ -1,21 +1,41 @@
...
+  | keyof JSX.IntrinsicElements
+  | Component<any>
+  | (string & {});
+
 export interface DefaultTheme {}
 export interface CSSAttribute extends CSSProperties {
   [key: string]: CSSAttribute | string | number | undefined;
 }
+type StylesGenerator<P = {}> =
+  (props: P) => CSSAttribute | string;
```
Comment (100terres) [inline src/index.d.ts:15]: :warning: not sure it returns a `CSSAtribute`

File: src/index.d.ts [hunk 2]
```diff
@@ -31,46 +51,35 @@ export declare function ThemeProvider<
...
-            class?: any;
-            children?: any;
-          }
-      ) => string | number | CSSAttribute | undefined)
-  )[]
-) => ((props: P & T) => JSX.Element) & {
-  class: (props: P & T) => string;
+export interface ThemeProp {
+  theme?: DefaultTheme;
+}
```
Comment (100terres) [inline src/index.d.ts:56]: This is would also us to override the props in a project with a theme with something like this:

```
// in a styled.d.ts file
declare module "solid-styled-components" {
  export interface DefaultTheme {
    // ...
  }

  // The theme will always be present
  export interface ThemeProp {
    theme: DefaultTheme;
    //   ^
    // The `?` was removed 
  }
```

We won't need to make sure that the theme exist on the `props` e.g.

```
const Button = styled("button")((props) => ({
  color: props.theme.typography.color,
  //          ^
  // we won't need to check if the theme is present or not
);
```

File: src/index.d.ts [hunk 3]
```diff
@@ -1,21 +1,41 @@
...
+  tag: TemplateStringsArray,
+  ...tagArgs: TagArgs
 ): void;
+export declare function css(styles: StylesArg): string;
 export declare function css(
-  tag: CSSAttribute | TemplateStringsArray | string,
-  ...props: Array<string | number>
+  tag: TemplateStringsArray,
+  ...tagArgs: TagArgs
 ): string;
```
Comment (100terres) [inline src/index.d.ts:39]: By [having multiple declarations](https://www.typescriptlang.org/docs/handbook/declaration-merging.html#merging-interfaces) we allow multiple arguments only when we use the "tag function", but when we do a regular function call can restirct the type to one argument.

```tsx
// allowed
css`
  color: ${theme.typography.color};
`
// allowed
css({
  color: ${theme.typography.color},
});

// now the following would be disallowed
css(
  {
    color: ${theme.typography.color},
  },
  {
    font-family: ${theme.typography.fontFamily, // this won't be applied
  },
);
```

File: src/index.d.ts (hunk 2 above)
Comment (100terres) [reply src/index.d.ts:56]: I could extract this in an other PR if needed.

**Comment by ryansolid** [comment]
Thank you

File: src/index.d.ts (hunk 2 above)
Comment (100terres) [reply src/index.d.ts:56]: This is not possible with the current version of TypeScript. I've added a comment on an existing issue on the TypeScript repo: https://github.com/microsoft/TypeScript/issues/33699#issuecomment-1275535308

Comment (100terres) [reply src/index.d.ts:56]: For now using the non-null assertion operator should do the trick:
```tsx
styled("span")`
  color: ${(props) => props.theme!.palette}
`;
```

File: src/index.d.ts [hunk 4]
```diff
@@ -31,46 +51,35 @@ export declare function ThemeProvider<
...
+  [element in keyof JSX.IntrinsicElements]: StylingFn<JSX.IntrinsicElements[element]>;
 };
 export declare function createGlobalStyles(
-  tag: CSSAttribute | TemplateStringsArray | string,
-  ...props: Array<string | number | Function>
-): Function;
+  tag: TemplateStringsArray,
+  ...tagArgs: TagArgs
+  ): () => null;
+export declare function createGlobalStyles(styles: StylesArg): () => null;
```
Comment (100terres) [inline src/index.d.ts:85]: I think the `theme` is available in the `createGlobalStyles`. I'll have a look and see if it can be added.
